"""initial

Revision ID: 4ea1e5e38ab1
Revises: 
Create Date: 2025-11-06 18:39:51.972421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea1e5e38ab1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campanhas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('DataCriacao', sa.String(), nullable=True),
    sa.Column('Ativa', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Campanhas_Id'), 'Campanhas', ['Id'], unique=False)
    op.create_table('Equipamentos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Tipo', sa.String(), nullable=True),
    sa.Column('Raridade', sa.String(), nullable=True),
    sa.Column('Icone', sa.String(), nullable=True),
    sa.Column('Ataque', sa.Integer(), nullable=True),
    sa.Column('Defesa', sa.Integer(), nullable=True),
    sa.Column('Bonus', sa.Integer(), nullable=True),
    sa.Column('Peso', sa.Integer(), nullable=True),
    sa.Column('Dano', sa.String(), nullable=True),
    sa.Column('Proficiencia', sa.String(), nullable=True),
    sa.Column('Campanha_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Equipamentos_Id'), 'Equipamentos', ['Id'], unique=False)
    op.create_table('Habilidades',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Tipo', sa.String(), nullable=True),
    sa.Column('Cooldown', sa.Integer(), nullable=True),
    sa.Column('Icone', sa.String(), nullable=True),
    sa.Column('Efeito', sa.Text(), nullable=True),
    sa.Column('Dano', sa.String(), nullable=True),
    sa.Column('Classes', sa.String(), nullable=True),
    sa.Column('Campanha_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Habilidades_Id'), 'Habilidades', ['Id'], unique=False)
    op.create_table('Magias',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Categoria', sa.String(), nullable=True),
    sa.Column('Nivel', sa.Integer(), nullable=True),
    sa.Column('Icone', sa.String(), nullable=True),
    sa.Column('CustoMana', sa.Integer(), nullable=True),
    sa.Column('Cooldown', sa.Integer(), nullable=True),
    sa.Column('Efeito', sa.Text(), nullable=True),
    sa.Column('Dano', sa.String(), nullable=True),
    sa.Column('Classes', sa.String(), nullable=True),
    sa.Column('Campanha_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Magias_Id'), 'Magias', ['Id'], unique=False)
    op.create_table('Racas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Passiva', sa.Text(), nullable=True),
    sa.Column('Caracteristica', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Racas_Id'), 'Racas', ['Id'], unique=False)
    op.create_table('Classe',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Habilidades_id', sa.Integer(), nullable=True),
    sa.Column('Magias_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Habilidades_id'], ['Habilidades.Id'], ),
    sa.ForeignKeyConstraint(['Magias_id'], ['Magias.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Classe_Id'), 'Classe', ['Id'], unique=False)
    op.create_table('Personagens',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Historia', sa.Text(), nullable=True),
    sa.Column('Tendencia', sa.String(), nullable=True),
    sa.Column('Level', sa.Integer(), nullable=True),
    sa.Column('Tipo', sa.String(), nullable=True),
    sa.Column('Vida', sa.Integer(), nullable=True),
    sa.Column('Forca', sa.Integer(), nullable=True),
    sa.Column('Destreza', sa.Integer(), nullable=True),
    sa.Column('Constituicao', sa.Integer(), nullable=True),
    sa.Column('Inteligencia', sa.Integer(), nullable=True),
    sa.Column('Sabedoria', sa.Integer(), nullable=True),
    sa.Column('Mana', sa.Integer(), nullable=True),
    sa.Column('Carisma', sa.Integer(), nullable=True),
    sa.Column('Sorte', sa.Integer(), nullable=True),
    sa.Column('Reputacao', sa.Integer(), nullable=True),
    sa.Column('CA', sa.Integer(), nullable=True),
    sa.Column('Deslocamento', sa.Integer(), nullable=True),
    sa.Column('Classe_Nome', sa.String(), nullable=True),
    sa.Column('Raca_Nome', sa.String(), nullable=True),
    sa.Column('Raca_id', sa.Integer(), nullable=True),
    sa.Column('Classe_id', sa.Integer(), nullable=True),
    sa.Column('Equipamento_id', sa.Integer(), nullable=True),
    sa.Column('Campanha_id', sa.Integer(), nullable=True),
    sa.Column('ImagemPath', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['Classe_id'], ['Classe.Id'], ),
    sa.ForeignKeyConstraint(['Equipamento_id'], ['Equipamentos.Id'], ),
    sa.ForeignKeyConstraint(['Raca_id'], ['Racas.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Personagens_Id'), 'Personagens', ['Id'], unique=False)
    op.create_table('Atributos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Personagem_id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Personagem_id'], ['Personagens.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Atributos_Id'), 'Atributos', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Atributos_Id'), table_name='Atributos')
    op.drop_table('Atributos')
    op.drop_index(op.f('ix_Personagens_Id'), table_name='Personagens')
    op.drop_table('Personagens')
    op.drop_index(op.f('ix_Classe_Id'), table_name='Classe')
    op.drop_table('Classe')
    op.drop_index(op.f('ix_Racas_Id'), table_name='Racas')
    op.drop_table('Racas')
    op.drop_index(op.f('ix_Magias_Id'), table_name='Magias')
    op.drop_table('Magias')
    op.drop_index(op.f('ix_Habilidades_Id'), table_name='Habilidades')
    op.drop_table('Habilidades')
    op.drop_index(op.f('ix_Equipamentos_Id'), table_name='Equipamentos')
    op.drop_table('Equipamentos')
    op.drop_index(op.f('ix_Campanhas_Id'), table_name='Campanhas')
    op.drop_table('Campanhas')
    # ### end Alembic commands ###
